import Head from 'next/head'
import Contact from '../component/Contact'
import HeaderPage from '../component/HeaderPage'
import {createClient} from 'contentful'

import s from '../styles/Home.module.scss'

export const getStaticProps=async()=>{
  const client=createClient({
    space:"5r8xso88q94y",
    accessToken:"viwGlOS3XAgC8R0RwkgWVfbzUrFSYoVfPJCh8-yMCKM"
  })
  const res=await client.getEntries({content_type:"carouzel"})

  
  return {
    props:{
      data:res.items
    }
  }
  
  }


export default function Home({data}) {

  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" 
  content="width=device-width, initial-scale=1.0, user-scalable=no"/>
        <meta name="description" content="Generated by create next app" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <header className={s.header}>
<Contact></Contact>
<HeaderPage data={data}></HeaderPage>

   </header>
   <main>

   </main>

   
 
    </div>
  )
}
