import Head from 'next/head'
import Contact from '../component/Contact'
import HeaderPage from '../component/HeaderPage'
import {createClient} from 'contentful'
import { useEffect, useRef,useState } from 'react'
import s from '../styles/Home.module.scss'
import World from '../component/World'
import Categories from '../component/Categories'
import { Participle } from '../FUNCTIONS/CANVAS/ParticpleClass'
import Footer from '../component/Footer'
import Canvas from '../component/Canvas'


export const getStaticProps=async()=>{
  const client=createClient({
    space:"5r8xso88q94y",
    accessToken:"viwGlOS3XAgC8R0RwkgWVfbzUrFSYoVfPJCh8-yMCKM"
  })
  const carouselImg=await client.getEntries({content_type:"carouzel"})
  const fullWork=await client.getEntries({content_type:"zdjecia"})

  
  return {
    props:{
      data:carouselImg.items,
      full:fullWork.items
    }
  }
  
  }


export default function Home({data,full}) {

useEffect(()=>{
  console.log(screen.width,"width")
console.log(screen.height,"height")
})
  const requestRef=useRef()
  const container=useRef()
  return (
    <div ref={container} className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" 
  content="width=device-width, initial-scale=1.0, user-scalable=no"/>
        <meta name="description" content="Generated by create next app" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Canvas container={container}></Canvas>
   <header className={s.header}>

<Contact></Contact>
<HeaderPage data={data}></HeaderPage>
<World></World>
   </header>
   <hr></hr>
   <main className={s.main}>
    <Categories full={full}></Categories>
  


   </main>
   <footer className={s.footer}>
   <Footer></Footer>
   </footer>

   

    </div>
  )
}
